export type TradeV4VisualState =
  | "floating"
  | "detected"
  | "locked"
  | "locked_for_buy"
  | "execution_submitted"
  | "position_opened_hold"
  | "pull_to_center"
  | "removed_from_scanner"
  | "approved"
  | "capturing"
  | "open"
  | "closed"
  | "rejected";

export type TradeV4CandidateView = {
  candidateId: string;
  symbol: string;
  price: number | null;
  rank: number | null;
  score: number | null;
  confidenceSource: string;
  source: string;
  riskGroup: string;
  strategy: string;
  status: "BUY" | "WAIT" | "BLOCK" | "AVOID";
  engineState: TradeV4VisualState;
  confidence: number;
  spreadPct: number | null;
  volumeRel: number | null;
  dipPct: number | null;
  reboundPct: number | null;
  tpRoomPct: number | null;
  momentum: number | null;
  mainReason: string;
  requiredNextAction: string | null;
  blockReasons: string[];
  mlBadEntryRisk: number | null;
  dataQuality: "GOOD" | "MEDIUM" | "BAD" | "UNKNOWN";
  isOrderLocked: boolean;
  referencePeriod?: "1h" | "4h" | "1d" | "1w";
  periodChangePct?: number | null;
  periodTrend?: "BULLISH" | "BEARISH" | "SIDEWAYS" | null;
  periodMomentum?: number | null;
  periodVolatility?: number | null;
  periodRegime?: string | null;
  effectiveStrategy?: string;
  groupRecommendedStrategy?: string;
  groupTrend?: string;
  displayTrend?: string;
  displayTrendSource?: string;
  strategySource?: string;
  autoStrategyReason?: string;
  autoStrategyWarnings?: string[];
  confidenceTier?: string;
  autoTpDecision?: {
    riskGroup: string;
    confidence: number;
    confidenceTier: string;
    tp1Pct: number;
    tp2Pct: number | null;
    source: string;
    rangeMin: number;
    rangeMax: number;
    usedMaxRange: boolean;
    reason: string;
    downgradedByMarket: boolean;
    downgradedBySafety: boolean;
  };
  strategyAudit?: import('../../core/strategy-audit/strategy-audit-types').StrategyAuditSnapshot | null;
  finalExecutable?: boolean;
  buyAllowed?: boolean;
  primaryBlocker?: string | null;
  gateAudit?: {
    spreadPct: number;
    maxSpreadSettingFromUI: number;
    maxSpreadUsedByEntryGate: number;
    slippagePct: number;
    maxSlippageUsed: number;
    spreadOk: boolean;
    slippageOk: boolean;
    blocker: string;
    sourceOfThreshold: string;
    strategy: string;
    riskGroup: string;
    autoBotsOn: boolean;
    manualOverrideOn: boolean;
    finalExecutable: boolean;
    buyAllowed: boolean;
    setupMissing: string[];
  };
};

export type TradeV4OpenPositionView = {
  id: string;
  symbol: string;
  entryPrice: number;
  refPrice?: number | null;
  livePrice: number;
  pnlPct: number;
  pnlUsd: number;
  tp1Pct: number | null;
  tp1TargetPrice?: number | null;
  tp1Source?: string | null;
  riskSnapshotStatus?: "VALID_RISK_SNAPSHOT" | "LEGACY_PRE_FIX" | "SNAPSHOT_MISSING" | "BUG_TP1_INVALID";
  sourceUsed?: "PositionManager" | "legacy_fallback";
  isLivePosition?: boolean;
  isLegacyPosition?: boolean;
  snapshotPresent?: boolean;
  riskSnapshotPresent?: boolean;
  entrySnapshotPresent?: boolean;
  tp2Pct: number | null;
  slPct: number | null;
  tp2Source?: string | null;
  slSource?: string | null;
  trailStartPct?: number | null;
  trailPullbackPct?: number | null;
  trailState: "off" | "armed" | "active";
  ageLabel: string;
  status: "open" | "watching" | "closing";
  strategy: string;
  riskGroup: string;
  groupTrend: string;
  exitStatus: "monitoring" | "tp_armed" | "trailing_active" | "sl_risk" | "closing" | "closed";
  priceQuality: "fresh" | "stale" | "fallback" | "pending" | "unavailable";
  ownerType?: string;
  sourceLabel?: string;
  mode?: string;
  executionMode?: string;
  executionAdapter?: string;
  entryRule?: string | null;
  entryReason?: string | null;
  entryPriceSource?: string | null;
  entryPriceAgeMs?: number | null;
  livePriceSource?: string | null;
  livePriceAgeMs?: number | null;
  spreadPct?: number | null;
  quantity?: number;
  usedCapitalUsd?: number;
  confidence?: number | null;
  score?: number | null;
  scannerPeriod?: string | null;
  candidateSource?: string | null;
  trailingEnabled?: boolean;
  dynamicTrailingEnabled?: boolean;
  trailStart?: string | number | null;
  trailPullback?: number | null;
  maxSlippagePct?: number | null;
  maxTotalCostPct?: number | null;
  entryConfirmation?: string | null;
  dipPct?: number | null;
  requiredDipPct?: number | null;
  reboundPct?: number | null;
  requiredReboundPct?: number | null;
  reboundConfirmed?: boolean | null;
  momentumConfirmed?: boolean | null;
  strategySetupSummary?: string | null;
  strategySetupDipReqLabel?: string | null;
  strategySetupReboundReqLabel?: string | null;
  strategySetupMomLabel?: string | null;
  strategySetupResult?: string | null;
  strategySetupWhy?: string | null;
  strategySetupSource?: string | null;
  strategySetupMissingFields?: string[];
  strategySetupMetrics?: Record<string, {
    actualValue: string | number | boolean | null;
    requiredValue: string | number | boolean | null;
    passed: boolean;
    usedByStrategy: boolean;
    role: 'required' | 'optional' | 'advisory' | 'blocker' | 'unused';
    sourceLayer: 'buy-rule-matrix' | 'autobots-selector' | 'auto-strategy-router' | 'trader-brain' | 'entry-gate' | 'legacy';
  }>;
  hasSnapshot?: boolean;
  baseAsset?: string;
  quoteAsset?: string;
  openedAtLabel?: string;
  strategySource?: string | null;
  marketRegimeAtEntry?: string | null;
  btcContextAtEntry?: string | null;
  dataQuality?: string | null;
  snapshotStatus?: "VALID_SNAPSHOT" | "LEGACY_MISSING_SNAPSHOT" | "BUG_MISSING_SNAPSHOT_NEW_POSITION" | "PARTIAL_SNAPSHOT";
  snapshotMissingFields?: string[];
  pnlBreakdown?: {
    entryPrice: number;
    livePrice: number;
    livePriceSource: string;
    qty: number;
    usedCapital: number;
    grossPnlUsd: number;
    grossPnlPct: number;
    feesEstimated: number;
    netPnlUsd: number;
    netPnlPct: number;
    formulaUsed: string;
    priceAgeMs: number;
    priceFreshness: "fresh" | "stale" | "fallback" | "pending" | "unavailable";
    fallbackUsed: boolean;
    reasonIfPriceUnavailable: string;
  };
  diagnostic?: {
    positionId: string;
    createdAt: string;
    source: string;
    mode: string;
    strategy: string;
    entryRule: string | null;
    autoBotsOnAtEntry: boolean;
    userSettingsSnapshotAtEntry: Record<string, unknown> | null;
    entryConfigSnapshot: Record<string, unknown> | null;
    strategyAuditSnapshot: Record<string, unknown> | null;
    strategySetupSnapshot: Record<string, unknown> | null;
    pnlCalcSummary: string;
    warnings: string[];
  };
};

export type TradeV4ClosedPositionView = {
  id: string;
  symbol: string;
  entryPrice: number;
  exitPrice: number;
  pnlPct: number;
  pnlUsd: number;
  closeReason: string;
  dataQuality: "GOOD" | "MEDIUM" | "BAD" | "UNKNOWN";
  mlEligibility: "eligible" | "analysis_only" | "not_eligible";
  strategy: string;
  openedAtLabel?: string;
  closedAtLabel: string;
  durationLabel: string;
  closePriceQuality: string;
  trainingEligible: boolean;
  ownerType?: string;
  sourceLabel?: string;
  modeLabel?: string;
  executionMode?: string;
  executionAdapter?: string;
  entryRule?: string | null;
  riskGroup?: string | null;
  fees?: number | null;
  netPnlUsd?: number | null;
  closePriceSource?: string | null;
  closePriceAgeMs?: number | null;
  realMarketPriceAtClose?: number | null;
  refPriceAtEntry?: number | null;
  tp1Pct?: number | null;
  tp1TargetPrice?: number | null;
  tp1HitPrice?: number | null;
  tp1Source?: string | null;
  riskSnapshotStatus?: "VALID_RISK_SNAPSHOT" | "LEGACY_PRE_FIX" | "SNAPSHOT_MISSING" | "BUG_TP1_INVALID";
  tp2Pct?: number | null;
  slPct?: number | null;
  trailPullbackPct?: number | null;
  dipPct?: number | null;
  reboundPct?: number | null;
  score?: number | null;
  confidence?: number | null;
  hasSnapshot?: boolean;
  marketTrendAtEntry?: string | null;
  groupTrendAtEntry?: string | null;
  marketRegimeAtEntry?: string | null;
  btcContextAtEntry?: string | null;
  dipReboundLabel?: string | null;
  snapshotStatus?: "VALID_SNAPSHOT" | "LEGACY_MISSING_SNAPSHOT" | "BUG_MISSING_SNAPSHOT_NEW_POSITION" | "PARTIAL_SNAPSHOT";
  snapshotMissingFields?: string[];
  pnlBreakdown?: {
    entryPrice: number;
    exitPrice: number;
    realMarketPriceAtClose: number;
    closePriceSource: string;
    qty: number;
    usedCapital: number;
    grossPnlUsd: number;
    grossPnlPct: number;
    fees: number;
    netPnlUsd: number;
    netPnlPct: number;
    closeReason: string;
    priceQuality: string;
    formulaUsed: string;
  };
};

export type TradingParametersView = {
  strategySource: 'autobots' | 'manual_override';
  entryConfirmationMode: 'strict' | 'smart' | 'aggressive';
  strategy: string;
  stopLossPct: number;
  tp1Pct: number;
  tp2Pct: number;
  refWindow: "AUTO" | "LAST_HOUR" | "LAST_DAY" | "LAST_3_DAYS" | "LAST_WEEK" | "LAST_3_WEEKS";
  refMode: "AUTO" | "SMA" | "EMA" | "VWAP" | "BOLLINGER";
  dynamicTrailingEnabled: boolean;
  trailTriggerPct: number;
  trailPullbackPct: number;
  scannerRiskGroups: {
    top_caps: boolean;
    large_caps: boolean;
    mid_caps: boolean;
    high_risk: boolean;
    very_high_risk: boolean;
  };
  scannerReferencePeriod: "1h" | "4h" | "1d" | "1w";
  scannerUniverseMode: "BINANCE_TOP_250" | "TOP_100" | "TOP_50" | "TOP_20" | "WATCHLIST";
  scannerUniverseSize: number;
  scannerFinalPoolSize: number;
  scannerBanlist: string[];
  maxSpreadPct: number;
  maxSlippagePct: number;
  maxTotalEntryCostPct: number;
  minVolumeRel: number;
  minMomentumPct: number;
  maxPriceAgeMs: number;
  antiFomoMode: 'off' | 'balanced' | 'strict';
  maxOverextensionPct: number;
  requirePullbackAfterPump: boolean;
  bollingerOverextensionGuard: boolean;
  maxEntriesPerCycle: number;
  maxEntryGateAttemptsPerScan: number;
  maxEntriesPerCoinPerDay: number;
  cooldownAfterBuyMs: number;
  cooldownAfterLossMs: number;
  paperAutoEnabled: boolean;
  autoTradingCapital: number;
  capitalPerCoin: number;
  reinvestProfit: boolean;
  maxOpenPositions: number;
  manualDipperSetup: {
    momentumMinReboundPct: number;
    momentumConfirmationRequired: boolean;
    balancedMinDipPct: number;
    balancedMinReboundPct: number;
    balancedWeakMomentumConfirmation: boolean;
    dipReboundMinDipPct: number;
    dipReboundMinReboundPct: number;
    conservativeMinDipPct: number;
    conservativeMinReboundPct: number;
  };
};

export type AirCoinView = {
  symbol: string;
  engineState: TradeV4VisualState;
  confidence: number;
  score: number | null;
  status: string;
  spreadPct: number;
  volumeRel: number;
  x: number; y: number; z: number;
  baseX: number; baseY: number; baseZ: number;
  phase: number; speed: number;
  captureProgress: number;
  pullProgress?: number;
  linkedPositionId?: string;
};

export interface TradeV4NoBuyDisplay {
  executionPoolSize: number;
  watchPoolSize: number;
  nearMissPoolSize: number;
  topReasons: string[];
  nearestCandidates: string[];
  requiredNextActions: string[];
  marketAction?: string;
  bestFit?: string;
  htf?: string;
  primary?: string;
  ltf?: string;
  marketConfidence?: number;
  marketBias?: string;
  topBlockers?: string[];
  requiredNextCondition?: string[];
  momentumPockets?: {
    detected: boolean;
    count: number;
    entries: Array<{
      symbol: string;
      momentum: number;
      riskGroup: string;
      status: string;
      blocker: string | null;
      confidence: number;
      strategy: string;
      volumeRel: number;
      spreadPct: number;
      priceAgeMs: number;
      tpRoomOk: boolean;
      entryGateRan: boolean;
      entryGatePassed: boolean;
      nextRequiredCondition: string;
    }>;
  };
  topMomentum?: Array<{ symbol: string; momentum: number; riskGroup: string; status?: string; blocker?: string | null; entryGatePassed?: boolean }>;
  topHighRiskMomentum?: Array<{ symbol: string; momentum: number; riskGroup: string; status?: string; blocker?: string | null }>;
  topVeryHighRiskMomentum?: Array<{ symbol: string; momentum: number; riskGroup: string; status?: string; blocker?: string | null }>;
  buyReadyCount?: number;
  blockedCount?: number;
  blockedBySpread?: number;
  blockedBySlippage?: number;
  blockedByDip?: number;
  blockedByRebound?: number;
  blockedByMomentum?: number;
  blockedByTpRoom?: number;
  blockedByTp1Invalid?: number;
  blockedByFinalExecutableFalse?: number;
  selectedForExecutionCount?: number;
  finalNoBuyReason?: string;
}

export interface TradeV4PageModel {
  candidates: TradeV4CandidateView[];
  openPositions: TradeV4OpenPositionView[];
  restoringOpenPositions?: boolean;
  closedPositions: TradeV4ClosedPositionView[];
  selectedSymbol: string | null;
  scannerRunning: boolean;
  engineOnline: boolean;
  mode: "PAPER" | "LIVE_LOCKED";
  capital: number;
  usedCapital: number;
  pnlToday: number;
  dataQuality: "GOOD" | "MEDIUM" | "BAD" | "UNKNOWN";
  publicDataReady: boolean;
  publicDataRefreshing: boolean;
  referencePeriod?: "1h" | "4h" | "1d" | "1w";
  marketPeriodTrend?: "BULLISH" | "BEARISH" | "SIDEWAYS" | null;
  marketPeriodChangePct?: number | null;
  marketPeriodVolatility?: number | null;
  btcPeriodTrend?: "BULLISH" | "BEARISH" | "SIDEWAYS" | null;
  ethPeriodTrend?: "BULLISH" | "BEARISH" | "SIDEWAYS" | null;
  executionPoolSize?: number;
  watchPoolSize?: number;
  nearMissPoolSize?: number;
  topExecutionCandidates?: string[];
  topWatchCandidates?: string[];
  noBuyDisplay?: TradeV4NoBuyDisplay;
  lastScanAt?: string | null;
  dipperCardState?: {
    sourceUsed: string;
    lastCanonicalUpdateAt: string | null;
    scannerStatus: "RUNNING" | "WAITING" | "STOPPED";
    candidateCount: number;
    engineReviewCount: number;
    openPositionsCount: number;
    closedTodayCount: number;
    marketTrend: "BULLISH" | "BEARISH" | "SIDEWAYS" | null;
    btcContext: "BULLISH" | "BEARISH" | "SIDEWAYS" | null;
    ethContext: "BULLISH" | "BEARISH" | "SIDEWAYS" | null;
    strategyRef: string;
    capitalUsedPct: number;
    availableCapital: number;
  };
  emptyUniverseReason?: string;
  paperAutoEnabled?: boolean;
  paperAutoResult?: {
    attempted: boolean;
    executed: boolean;
    blocked: boolean;
    symbol: string;
    reason: string;
    gateResults: string[];
    stage?: 'PreCheckPassed' | 'ExecutionSubmitted' | 'DemoFillCreated' | 'PaperFillCreated' | 'PositionOpened' | 'ExecutionFailed';
    adapterCalled?: boolean;
    adapterResult?: string;
    positionCreateAttempted?: boolean;
    positionCreated?: boolean;
    openPositionsBefore?: number;
    openPositionsAfter?: number;
  };
  autoStrategySummary?: {
    totalCandidates: number;
    conservative: number;
    balanced: number;
    momentum: number;
    dip_and_rebound: number;
    wait: number;
    avoid: number;
    downgrades: number;
    referencePeriod: string;
  };
  btcAnchorEnabled?: boolean;
  ethAnchorEnabled?: boolean;
  executionPlan?: {
    canExecute: boolean;
    selectedCandidates: Array<{
      symbol: string;
      rank: number;
      status: string;
      effectiveStrategy: string;
      groupTrend: string;
      groupRecommendedStrategy: string;
      confidence: number;
      score: number;
      plannedAction: string;
      reason: string;
      requiredChecks: string[];
    }>;
    skippedCandidates: Array<{
      symbol: string;
      status: string;
      reason: string;
      gate: string;
      isRetryable: boolean;
    }>;
    noBuyReasons: string[];
    executionPoolSize: number;
    watchPoolSize: number;
    nearMissPoolSize: number;
    maxEntriesPerCycle: number;
    availableSlots: number;
    capitalAvailable: number;
    decisionMode: string;
    executionAdapter: string;
  };
  scalperState?: {
    enabled: boolean;
    status: string;
    candidates: number;
    executionPool: number;
    watchPool: number;
    lastScanAt: string | null;
    lastBlockReason: string | null;
    openScalpPositions: number;
    settings: {
      mode: 'manual' | 'auto';
      allowedRiskGroups: string[];
      scanEverySec: number;
      pollEverySec: number;
      stalePriceSec: number;
      maxOpenScalpPositions: number;
      maxScalpCandidates: number;
      tp1Pct: number;
      tp2Pct: number;
      stopLossPct: number;
      trailingEnabled: boolean;
      trailTriggerPct: number;
      trailPullbackPct: number;
      maxSpreadPct: number;
      minVolumeRelative: number;
      minMomentumPct: number;
      requireFreshPrice: boolean;
      paperOnly: boolean;
    };
  };
}
